### ISSUE TITLE
Error message when Eigen is missing

### ISSUE THREAD

**Issue by chjost** [maowerner/sLapH-contractions#7]
I am not sure if this is a real issue, however I would like to have a guideline here (possibly a Wiki page).

When trying to compile the code on Jureca I get an error due to Eigen3 not being found. As far as I know Eigen themself do not provide a EigenConfig.cmake file, at least it is not available on Jureca.

This problem can be fixed by setting "-D EIGEN3_INCLUDE_DIR=/path/to/eigen3" or providing our own  EigenConfig.cmake file.

What is the most useful way to go about this?

**Comment by martin-ueding** [comment]
This is “solved” by supplying the `EIGEN3_INCLUDE_DIR` in the current setup. We have build scripts for QBiG and JURECA. Providing a `FindEigen.cmake` file would be possible, but that would not help with local installations anyway.

**Comment by kostrzewa** [comment]
An option might be to copy what QUDA does, which is to simply download Eigen...

**Comment by martin-ueding** [comment]
Since Eigen does not have dependencies itself *and* is header only, this is actually feasible. But I do not really want such dependency management code in this program. We can happily give a good error message, but I think that the user should install the dependencies on their own. Likely there is a better way than downloading it (module system, Debian/RPM package).

Or we go the Google way and include a convenience copy of Eigen in this code and eventually start modifying it …
